syntax = "proto3";
package kyuubi.auth;
option java_package = "org.apache.kyuubi.server.grpc.proto";
option java_outer_classname = "SparkConnectAuthProto";
option java_multiple_files = true;

service SparkConnectAuthService {
  rpc GetToken    (GetTokenRequest)    returns (GetTokenResponse);
  rpc RenewToken  (RenewTokenRequest)  returns (RenewTokenResponse);
  rpc RevokeToken (RevokeTokenRequest) returns (RevokeTokenResponse);
}

message GetTokenRequest   {}
message GetTokenResponse  { string token = 1; int64 expires_at_ms = 2; }
message RenewTokenRequest  { string token = 1; }
message RenewTokenResponse { int64 expires_at_ms = 1; }
message RevokeTokenRequest  { string token = 1; }
message RevokeTokenResponse {}
