#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Spark 3.5.5 with Scala 2.13 (official apache/spark:3.5.5 is Scala 2.12).
# Built by compose (spark3-master/worker). Image tag: SPARK3_IMAGE in env/.env.

ARG BASE_IMAGE=eclipse-temurin:17-jdk-jammy
ARG SPARK3_TGZ_URL=https://archive.apache.org/dist/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3-scala2.13.tgz

FROM ${BASE_IMAGE}

ARG SPARK3_TGZ_URL

RUN apt-get update \
 && apt-get install -y --no-install-recommends curl bash tini procps \
 && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME=/opt/spark
ENV PATH="${SPARK_HOME}/bin:${PATH}"

RUN curl -fsSL "${SPARK3_TGZ_URL}" \
  | tar -xz -C /opt \
 && mv /opt/spark-3.5.5-bin-hadoop3-scala2.13 /opt/spark

WORKDIR /opt/spark
