# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kyuubi import spark_connect_auth_pb2 as kyuubi_dot_spark__connect__auth__pb2


class SparkConnectAuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetToken = channel.unary_unary(
                '/kyuubi.auth.SparkConnectAuthService/GetToken',
                request_serializer=kyuubi_dot_spark__connect__auth__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=kyuubi_dot_spark__connect__auth__pb2.GetTokenResponse.FromString,
                )
        self.RenewToken = channel.unary_unary(
                '/kyuubi.auth.SparkConnectAuthService/RenewToken',
                request_serializer=kyuubi_dot_spark__connect__auth__pb2.RenewTokenRequest.SerializeToString,
                response_deserializer=kyuubi_dot_spark__connect__auth__pb2.RenewTokenResponse.FromString,
                )
        self.RevokeToken = channel.unary_unary(
                '/kyuubi.auth.SparkConnectAuthService/RevokeToken',
                request_serializer=kyuubi_dot_spark__connect__auth__pb2.RevokeTokenRequest.SerializeToString,
                response_deserializer=kyuubi_dot_spark__connect__auth__pb2.RevokeTokenResponse.FromString,
                )


class SparkConnectAuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SparkConnectAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=kyuubi_dot_spark__connect__auth__pb2.GetTokenRequest.FromString,
                    response_serializer=kyuubi_dot_spark__connect__auth__pb2.GetTokenResponse.SerializeToString,
            ),
            'RenewToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewToken,
                    request_deserializer=kyuubi_dot_spark__connect__auth__pb2.RenewTokenRequest.FromString,
                    response_serializer=kyuubi_dot_spark__connect__auth__pb2.RenewTokenResponse.SerializeToString,
            ),
            'RevokeToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeToken,
                    request_deserializer=kyuubi_dot_spark__connect__auth__pb2.RevokeTokenRequest.FromString,
                    response_serializer=kyuubi_dot_spark__connect__auth__pb2.RevokeTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kyuubi.auth.SparkConnectAuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SparkConnectAuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kyuubi.auth.SparkConnectAuthService/GetToken',
            kyuubi_dot_spark__connect__auth__pb2.GetTokenRequest.SerializeToString,
            kyuubi_dot_spark__connect__auth__pb2.GetTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenewToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kyuubi.auth.SparkConnectAuthService/RenewToken',
            kyuubi_dot_spark__connect__auth__pb2.RenewTokenRequest.SerializeToString,
            kyuubi_dot_spark__connect__auth__pb2.RenewTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RevokeToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kyuubi.auth.SparkConnectAuthService/RevokeToken',
            kyuubi_dot_spark__connect__auth__pb2.RevokeTokenRequest.SerializeToString,
            kyuubi_dot_spark__connect__auth__pb2.RevokeTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
