# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyuubi/spark_connect_auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fkyuubi/spark_connect_auth.proto\x12\x0bkyuubi.auth\"\x11\n\x0fGetTokenRequest\"8\n\x10GetTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\rexpires_at_ms\x18\x02 \x01(\x03\"\"\n\x11RenewTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"+\n\x12RenewTokenResponse\x12\x15\n\rexpires_at_ms\x18\x01 \x01(\x03\"#\n\x12RevokeTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x15\n\x13RevokeTokenResponse2\x83\x02\n\x17SparkConnectAuthService\x12G\n\x08GetToken\x12\x1c.kyuubi.auth.GetTokenRequest\x1a\x1d.kyuubi.auth.GetTokenResponse\x12M\n\nRenewToken\x12\x1e.kyuubi.auth.RenewTokenRequest\x1a\x1f.kyuubi.auth.RenewTokenResponse\x12P\n\x0bRevokeToken\x12\x1f.kyuubi.auth.RevokeTokenRequest\x1a .kyuubi.auth.RevokeTokenResponseB>\n#org.apache.kyuubi.server.grpc.protoB\x15SparkConnectAuthProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kyuubi.spark_connect_auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#org.apache.kyuubi.server.grpc.protoB\025SparkConnectAuthProtoP\001'
  _globals['_GETTOKENREQUEST']._serialized_start=48
  _globals['_GETTOKENREQUEST']._serialized_end=65
  _globals['_GETTOKENRESPONSE']._serialized_start=67
  _globals['_GETTOKENRESPONSE']._serialized_end=123
  _globals['_RENEWTOKENREQUEST']._serialized_start=125
  _globals['_RENEWTOKENREQUEST']._serialized_end=159
  _globals['_RENEWTOKENRESPONSE']._serialized_start=161
  _globals['_RENEWTOKENRESPONSE']._serialized_end=204
  _globals['_REVOKETOKENREQUEST']._serialized_start=206
  _globals['_REVOKETOKENREQUEST']._serialized_end=241
  _globals['_REVOKETOKENRESPONSE']._serialized_start=243
  _globals['_REVOKETOKENRESPONSE']._serialized_end=264
  _globals['_SPARKCONNECTAUTHSERVICE']._serialized_start=267
  _globals['_SPARKCONNECTAUTHSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
